package Models;
// Generated May 9, 2018 4:20:00 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer idEmployee;
     private String firstName;
     private String lastName;
     private String jobTitle;
     private Date dateHired;

    public Employee() {
    }

    public Employee(String firstName, String lastName, String jobTitle, Date dateHired) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.jobTitle = jobTitle;
       this.dateHired = dateHired;
    }
   
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Date getDateHired() {
        return this.dateHired;
    }
    
    public void setDateHired(Date dateHired) {
        this.dateHired = dateHired;
    }




}


